#-------------------------------------------------------------------------
#
# Makefile for backend/qx/scheduler
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/scheduler
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_scheduler.o

include $(top_srcdir)/src/backend/common.mk
