#-------------------------------------------------------------------------
#
# Makefile for backend/qx/replication
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/replication
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_semantic_log.o

include $(top_srcdir)/src/backend/common.mk
