#-------------------------------------------------------------------------
#
# Makefile for backend/qx/planner
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/planner
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_agent_planner.o

include $(top_srcdir)/src/backend/common.mk
