#-------------------------------------------------------------------------
#
# Makefile for backend/qx/memory
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/memory
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_memory.o

include $(top_srcdir)/src/backend/common.mk
