#-------------------------------------------------------------------------
#
# Makefile for backend/qx/observe
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/observe
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_observe.o

include $(top_srcdir)/src/backend/common.mk
