#-------------------------------------------------------------------------
#
# Makefile for backend/qx/recovery
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/recovery
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_recovery.o

include $(top_srcdir)/src/backend/common.mk
