#-------------------------------------------------------------------------
#
# Makefile for backend/qx/security
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/security
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_security.o

include $(top_srcdir)/src/backend/common.mk
