#-------------------------------------------------------------------------
#
# Makefile for backend/qx/runtime
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/runtime
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_runtime.o \
	qx_container_backend.o \
	qx_microvm_backend.o \
	qx_runtime_policy.o \
	qx_backend_supervisor.o

include $(top_srcdir)/src/backend/common.mk
