#-------------------------------------------------------------------------
#
# Makefile for backend/qx/runtime
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/runtime
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_runtime.o

include $(top_srcdir)/src/backend/common.mk
