#-------------------------------------------------------------------------
#
# Makefile for backend/qx/executor
#
#-------------------------------------------------------------------------

subdir = src/backend/qx/executor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	qx_agent_executor.o

include $(top_srcdir)/src/backend/common.mk
