#-------------------------------------------------------------------------
#
# Makefile for backend/qx
#
#-------------------------------------------------------------------------

subdir = src/backend/qx
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = planner executor replication runtime memory

include $(top_srcdir)/src/backend/common.mk
